/**
 * Supplement Intelligence Articles Worker
 * Serves HTML articles stored in GitHub repository
 * Auto-generated by Twin agent - Batch 1 of 6 (5/27 articles live)
 * Last updated: 2026-03-04T07:17:22.723Z
 */

const GITHUB_RAW_BASE = 'https://raw.githubusercontent.com/johnfoster1012-pixel/supplement-intelligence/main/articles/';

const VALID_SLUGS = new Set([
  'v-glutation-benefits',
  'collagen-benefits',
  'v-asculax-benefits',
  'v-control-benefits',
  'v-fortyflora-benefits'
]);

addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request));
});

async function handleRequest(request) {
  const url = new URL(request.url);
  const path = url.pathname;
  
  // Handle /articles/[slug] or /articles/[slug].html
  const match = path.match(/^\/articles\/([a-z0-9-]+?)(\.html)?$/);
  
  if (!match) {
    return new Response('Not Found', { status: 404 });
  }
  
  const slug = match[1];
  
  if (!VALID_SLUGS.has(slug)) {
    return new Response('Article Not Found', { 
      status: 404,
      headers: { 'Content-Type': 'text/plain' }
    });
  }
  
  // Fetch from GitHub raw
  const githubUrl = GITHUB_RAW_BASE + slug + '.html';
  
  try {
    const response = await fetch(githubUrl, {
      headers: { 'User-Agent': 'Supplement-Intelligence-Worker/1.0' }
    });
    
    if (!response.ok) {
      return new Response('Article temporarily unavailable', { 
        status: 503,
        headers: { 'Content-Type': 'text/plain' }
      });
    }
    
    const html = await response.text();
    
    return new Response(html, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'public, max-age=3600',
        'X-Powered-By': 'Supplement Intelligence',
      }
    });
  } catch (err) {
    return new Response('Error fetching article: ' + err.message, { 
      status: 500,
      headers: { 'Content-Type': 'text/plain' }
    });
  }
}
